### PR TITLE
Added left and right side click handlers (/client/src/index)

### PR DESCRIPTION
**Pull request by jw642459986**
I added the left and right side click handlers to the main app module. These methods handle the 'shifting' of the carousel, that is, when a user clicks the right arrow button to display the next item on the right, or the left arrow button to display the next item on the left.

### CODE REVIEW

**Comment by jw642459986** [comment]
@Ahmed-Elawad

**Review by Ahmed-Elawad — COMMENTED** [review]
`const axios = require('axios');

module.exports = {
    getFurnitures: () => {
        return axios.get('/relatedFurnitures');
    }
} `
You can define the method right on the module.exports object in your server/controllers/index.js unless you were going to add more methods.

**Comment by Ahmed-Elawad** [comment]
`this.state = {
            data: [],
            displayed: [],
            //index of first element of displayed items
            first: 0,
            //index of last element of displayed items
            last: 0
        }`

I would also look at renaming your data state property to something more obvious like images. Other than that LGTM.

**Comment by jw642459986** [comment]
> `const axios = require('axios');
> 
> module.exports = {
> getFurnitures: () => {
> return axios.get('/relatedFurnitures');
> }
> } `
> You can define the method right on the module.exports object in your server/controllers/index.js unless you were going to add more methods.

Yes! I do plan to add more methods down the road. Thanks for the review!

**Pull request merged**
