### PR TITLE
finished the Carousel Component; need to add css

### PR DESCRIPTION
**Pull request by jw642459986**
I finished the carousel component; I just need to add some animations and css and maybe change the html tags a little to adjust their positions. 
Here is a link to the demo [https://recordit.co/QHwXyq73VI]

### CODE REVIEW

**Comment by jw642459986** [comment]
@hongmm Hey Matt, can you take a look at this for me please? Thanks <3

**Review by hongmm — APPROVED** [review]
Looks ok to me, I assume it loads on your end? In terms of code I think its fine. Also you should gitignore the bundle stuff since its going to update every time you make a change and its ginormous/nobody is going to check the bundle

**Review by jonathandavidlewis — COMMENTED** [review]
You need to ignore your dist folder. It has been committed, which you do not want. Please fix this and get ./dist out of your version control. :)

**Comment by jonathandavidlewis** [comment]
@jw642459986 Please include an image on your prs that have front end component additions / changes.

**Pull request merged**
