### PR TITLE
Implemented flexbox & rating stars

### PR DESCRIPTION
**Pull request by jw642459986**
Implemented flexbox & rating stars.
I also added some css using styled components. 
I plan to store the styled components in a separate file down the road.

### CODE REVIEW

**Comment by jw642459986** [comment]
@augustdolan Hey August, can you take a look at this for me? Thanks :)

**Review by augustdolan — CHANGES_REQUESTED** [review]
Hey @jw642459986 ,

Could you add a jpeg of your front end so I can compare your code with the results?

Cheers!
August

**Comment by jw642459986** [comment]
PR screenshot
@augustdolan Here it is!

**Review by augustdolan — APPROVED** [review]
client/src/index.jsx

- It looks like you have some unstyled components. I would either style them before the pull or delete them. 

- With react components, you want to use camel case, such as leftButton/LeftButton and not snake case like you did "Left_Button"

**Pull request merged**
